language: java
jdk: openjdk10
services:
- postgresql
env:
- JDBC_DATABASE_URL="jdbc:postgresql:calendue_travis"
before_script:
- psql -c 'create database calendue_travis;' -U postgres
install:
- npm install -g newman
script:
- cd server/
- ./build.sh -t
deploy:
  provider: heroku
  api_key:
    secure: "3de39ea0-ccea-411f-bd96-ac02fa3137dd"
  app: calendue
